* UNIT REVIEW
  [[file:~/Documents/notes/sm2025/HIST1302/u1/reviewGuide.pdf][Review Guide]]

[[file:~/Documents/notes/sm2025/HIST1302/u1/17-TheContestedWest-1865-1900.pdf][Chapter 17]]
* Ch 17
** Manifest Destiny
   Defined as the god given right to spread civilization from the atlantic coast to the pacific coast

** Native Reservations resembled colonial societes

    
* Ch 18
** Federal State and local government aided the development of railroads.

*** Federal money wash pushed into the big railroad companies to fuel westward expansion

*** 

* Ch 19 The City and Its Workers 1870-1900

** The brooklyn bridge
   It showcased the US' industrial revolution becuase it symbolized the advent of new technology and societal
   progress
   was built upon the backs of hardwroking labors


** Global migration
   Increased inustrialization and urbanization
   More people than cities could fit
   "Old immigrants" =  People from GB and other W EU countries -- Pioneer settlers
   New Immigrants = Eastern Europeans, Italians, Hungarians, E Eu Jews, Turks, Armeniansm Poles, Russians, and Other slavic people -- unskilled laborers
   Mainly a perceptive different

   There was prejudice and xenophobia towards these new laborers
   not any different from The original immigrants

** Experience of African Americans who migrated from the south to northeern cities in the Gilded Age
   Cities provide economic oppurtiny and escape from segregationa and discriminiation
   Racism -> confided to poor jobs and sub-par living conditions

** Jacob Riis' How the Other half Lives
   Showcased many photos among other things that showcase the terrible conditions of the slums
   Critized the "ill-spent wealth" that caused the tenements
** Women entering the white collor work force
   Women became typewriters and salesclearks, doing more "civilized" work
   White educated women who could read were good at recordkeeping
   Educated men had too many career choices so employers turned to women
   90% of the female clerical force was secrterial work
   Consumer cul up -> women work in department storefronts
   Macy's
   Only white women can be for customers work
   Black women worked in the back of the store


** Great RR Strike of 1877 -> Growth of Labor Unions
   1873 Depression-> Huge Layoffs and wage cuts
   The Baltimore and Ohio (B&O) RR anounced a 10% wage cut and a 10% divident to stockholders
   basically took their salary and gave it to stockholders
   brakemen in West Virgina NOT HAPPY
   Brought about great RR Strike of 1877
   100k RR workers walked off 
   caused sympathy -> 500k more leave
   No leadership but it spread like wildfire, even interntationally
   Rutherfored B Hayes sent army to run the trains and protec strike breakers 
   set precedent for mil response to strikes
   Violence eventually erupted in pitsburgh -> mil sent in
   basically became a rebellion, $2m in dmgs 
   Middle class americans were supportive until the damages violated property rights
   Middle class loves property rights so now the middle class became hostile

** The Knights of LaborA
   Membership up bc 1877 RR strike
   used to be secret but became public in 1878
   Anyone can join, it went based gender and raceial, and ideological lines

   Directioned by Grand Master Workman Terence V. Powderly

   Leonora Barry sereved as the gerneral investigator for womens work and helped them recruit a lot of women works
   Women = 20% and they had 95k blacks
   Didn't allow loywers, gamblers, stock brokers, bankers, and liquor dealers


** American Federation of Labor 
   Samuel Gompers = leader
   Orgnize skilled workers such as machinists and locomotive enginers
   becuase they hevae the best bargaining power
   Small membershup but grew later

** Hey Market Bombing
    Radical Socialists and anarchists wanted a social revolution
   Radicales led by Spies and Parsons allegedyl
   Set May 1 1886 as the global general workers strike, all of em wnet to chicago
   KoL refuse to endorse but many members go anyway 
   80k people outside McCormick mechanical reapers in chicago
   Strikebreakers replace jobs
   2 days later it gets violent and ppl atk the strikebreakers, protected by the police
   only 2k by day 3m 
   People atk police and someon throw a bomb

   Led to bad opinion of anarchists, labor unionsm strikers, immigrants, and the working class in general

   8men, including parsons and spies went on trial

   Parsons wasnt even their :cry:

   KoL collapse
   Many people turn to the AFL

** Cult of Domesticity
   ideal middle-class white-womanhood predominated from 1820 to the end of the century
   Led to the decline of the hired girl and the rise of the domestic servant who lived in the house
   15-30% of households had live in deomstic servants (90% women)
   Irish Bridgit
   South use blacks
   Freed white women and let them explore the world
   led to womens clubs, activists, temperence, etc.

** Municpal governments
  Led to vastly increased infastructure, streetsm lamposts, sewage, etc.
   Modern skyscraper
   paved rodes


** party Boss
   Political leader in Municpal governments
   Corrupt and criminal
   Got stuff done

** Party "machine"
   political party organized at the grassroots level
   win elections and reward voters with jobs on city payrool
   spoil system type beat
   NYC's = Tammany Hall
   did a lot of good yet corrupt
   William Marcy "Boss" Tweed
   Did good but caught taking tax oayer money


** The World's Columbian Exposiitoin
   Grandest world's fair in history
   Built an amazing white city 
   Beuatiful culture and innovations
   extravagent buildings, people sell everything to be here
   Winter came and people had to where to live --> Live in the white city buildings
   Conflict between troops and striking workers burned the entire city bc it was made cheaply and quickly
   Shows gilded age becuase it was beautiful and pretty, but dirty on the inside and built by chearp workers

* Ch 20 Dissent, Depression, & War 1890-1900
** Farmers are facing big issues
   The prices to sell crops are super low -> farmers cant repay loans
   The banks reposese the land
   Farmers form allances

** Populist Party = People's party
   Wanted a subtreasurey-- alowing farmers to store crops till prices up and recieve credit from gove
   land reform, plan to reclaim excessive land from rr
   wanted gov to own railroad system and telegraphs
   and get rid of the unfair rebates
   free silver
   direct senoator election
   support issues by means of referendum
   

** Problems of industrial laborers
   Wanted control of the shop florr
   long hours
   low wages


** Consequences of Homestead steel lockout
   Public opinion disliked the workers
   Frick's effort linked anarchism, as well as well as anything else the us didnt like with unions
   Carnagie also lost repution for ignoring it
   Union leaders blacklisted, the twelve hour day was back and 500 jobs gone
   steel workes make $2 a day
   The fataliesites increased 25%
   Carnagies prod trippled
   tho he kinda feel bad

** Labor action that demonstrated the power of the government in the nation's labor wars
   The government calling in the national guard showcased their power
   The courts would be in favor of property rights, which were often violated by striking workers
   It came down to laborers vs property and in the governmetn courts, property won
   The government also showcased they had the power to put people in jail
   They said that anyone who joined the pullman strike and supported the pullman railroad boycott would 
   be thrown in jail -- a direct jab at Eugene Debs
   Illinois governer did not want to bring in national guard, but attorney general Olney say that mail is violated --> justification to bring in gurard


** Injuction was used to break the pullman strike
   The injuction was a policy made by 2 chicago judges that made boycotting a crime punishable via jail
   This eventully lead to Debs being jailed, he was the only thing keeping the boycott's violence at bay
   Without him people switched to violence and the boycott ended swiftly
   

** The Founder of the socialist Party in America is none other than Euguene V Debs, who went into jail a trade unionist, and came out a socialist, he had tried the populist party, but didn't like it that much so he formed the socialist party and ran for president 5 times, 1900, 1904, 1908, 1912, 1920

** Rationale behind women's support for termeperence
   Women feel vulnerable to the effects of drunkness
   They were depedent on theri husbands wages, when a husband wasted money on alchohol, that meant less food for his wife and kids
   There was also abuse caused by drunken men


** Frances Willard use the "cult of domesticy" to argue for womens suffrage
   She used it as a shrewed pol tactic
   home protection = buzz word
   said that women needed to vote in order to protect their home and family; domestic life

** The most prominent issue of the presidential election of 1896, championed by candidate William Jennings Bryan 
   For the democrat-people's party, there were 2 major shortcomings for this election:
   1) The fusion of the democratic and people's party
      Some of the democrats disdained the actions of their party and left to join the people's party
      Some democrats think the people's party were extremist
      So a lot of people were unhappy with the combination of the 2
      Especially with the vice president, a big buisness banking dude who was meant to appeass conservative democrats, this guy angreed the people's party people
      This ended up spliting the vote for the populists, ensuring their party under-performed and ensuring that the democrats would not get as many populist votes as anticipated
   2) The battle of the standards
      The big buisnesses really did not want to have silver standard
      So they pushed a lot of propaganda saying that the free silver movement would only lower wages
      This would scare away the labor vote for the democrat-people's party
** The factors that prompted America's overseas expansion by the 1890s
   We have big industries here in the us but are people are so broke that they cant buy or shit
   So we gotta find some other place to do buisness
   Plus nationalism -- manifesting that destiny
   Basically we god momentum


** The foreign policy that established the western hemisphere as an american sphere of influence was the Monroe Doctrine
   It like didn't do shi back when james monroe made it, but now we used it as an excuse to like take land in LA
   We fought to get rid of EU influence in LA
   Panama canal type beat


** Consequences of John Hay's open-door policy in china
   No colonial empire but the US is garunteed acess to trade in china
   Maintained chinse soverignty
   Actually have ALL foreign powers equal access to the China trade

** What motivated the US to go to war with spain
   Basically we had $150m invested in Cuba
   Spain came in and all of that went to 0 becuase cubans fought for indep

   Plus the monroe doctrine

   Also: Spain was putting the cubans in these labor camps
   It was a psuedo civilization mission
   The main appeal to the public was that it was a humanitarian mission to end the sufferring of the cubans



** The new American empire 
   Consisted of many new territories
   Purto Rico, Guam
   Cuba was not technically a territory but had US rule
   The phillipennes had been fighting a war vs. the Spanish for indep, now they fought US and lost(long conflict) --> Us keep phillipennes till 1946
   We eventually took Hawaii forcefully

   The minority (Democrats and Populists) say that we have become the oppressors that we once fought against 
   The majority say that we are ministering angels, not despots

